### ISSUE TITLE
demo安装包不能安装

### ISSUE THREAD

**Issue by pengbs** [xmuSistone/android-drag-square#1]
提供的demo安装包安装提示解析错误，无法安装

**Comment by xmuSistone** [comment]
你用其它手机或者genymotion试试看。亦或者你用studio自己跑一下代码，我拿不到手机，所以这个暂时没法定位的。

**Comment by pengbs** [comment]
其他手机也一样，只能自己跑一下代码

**Comment by xmuSistone** [comment]
恩，那你跑一下代码。我这边的测试手机都是ok的~没有遇到无法安装的情况
