### ISSUE TITLE
DragView第一次绘制的时候出现了偏移

### ISSUE THREAD

**Issue by Txxyyy** [xmuSistone/android-drag-square#4]
谢谢楼主的分享，第一次执行onlayout的时候会出现偏移，请问有知道是什么原因导致呢？有什么好的解决的方式呢？
![image](https://user-images.githubusercontent.com/20162834/44378304-54d59a00-a533-11e8-9e7f-ec1f266b844c.png)

**Comment by poikl369** [comment]
第一次位置没有计算出来，我估计你开始设置了这个view为gono

**Comment by Wkongge** [comment]
> 第一次位置没有计算出来，我估计你开始设置了这个view为gono
demo 直接运行的， 也是出现上情况，并没有设置View 未 gone

**Comment by xmuSistone** [comment]
这个是安卓8.0以上的版本会有问题，8.0以下是OK的。刚看到，我今天修复下。

**Comment by xmuSistone** [comment]
@Txxyyy @poikl369 @Wkongge 问题已修复，代码已提交。

从运行结果结合断点调试，能够看到的是itemView.setLayoutParams()之后，itemView内部的子View并没有感知到其父View宽和高的变化。所以，我在itemView.layout方法之后，我又调用了一次itemView.requestLayout()方法，运行起来确实没问题了。
```java
if (firstLayout) {
      itemView.requestLayout();
}
```
